version: "3.7"
services:
  epso-jobs-crawler:
    build: .
    environment:
      # define your own environment variables via .env file

      # AWS
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      # Postgres DB settings
      # PG_HOST: host.docker.internal
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
    restart: unless-stopped
    ports:
      - "9999:8080"
  