-- Table: public.cities

-- DROP TABLE IF EXISTS public.cities;

CREATE TABLE IF NOT EXISTS public.cities
(
    id serial,
    code text NOT NULL,
    name text NOT NULL,
    country text,
    CONSTRAINT cities_pkey PRIMARY KEY (id),
    CONSTRAINT cities_code_ukey UNIQUE (code)
);

-- <option value="(\d+)">([^(]*)\((.*)\)</option>
-- ($1, '$2', LOWER('$2'), '$3'),

INSERT INTO cities (id, name, code, country) VALUES
(1221, 'Aalborg', LOWER('Aalborg'), 'Denmark'),
(5358, 'Limerick', LOWER('Limerick'), 'Ireland'),
(5357, 'Mariager', LOWER('Mariager'), 'Denmark'),
(5569, 'Marseille', LOWER('Marseille'), 'France'),
(5658, 'Zagreb', LOWER('Zagreb'), 'Croatia'),
(1171, 'Alicante', LOWER('Alicante'), 'Spain'),
(1218, 'Amsterdam', LOWER('Amsterdam'), 'The Netherlands'),
(1175, 'Angers', LOWER('Angers'), 'France'),
(1216, 'Athens', LOWER('Athens'), 'Greece'),
(1214, 'Bangkok', LOWER('Bangkok'), 'Thailand'),
(1201, 'Barcelona', LOWER('Barcelona'), 'Spain'),
(1231, 'Berlin', LOWER('Berlin'), 'Germany'),
(1151, 'Bilbao', LOWER('Bilbao'), 'Spain'),
(1225, 'Bonn', LOWER('Bonn'), 'Germany'),
(1149, 'Brussels', LOWER('Brussels'), 'Belgium'),
(1223, 'Bratislava', LOWER('Bratislava'), 'Slovakia'),
(1234, 'Bucharest', LOWER('Bucharest'), 'Romania'),
(1194, 'Budapest', LOWER('Budapest'), 'Hungary'),
(1232, 'Cadarache', LOWER('Cadarache'), 'France'),
(1195, 'Cologne', LOWER('Cologne'), 'Germany'),
(1197, 'Copenhagen', LOWER('Copenhagen'), 'Denmark'),
(1187, 'Dublin', LOWER('Dublin'), 'Ireland'),
(1200, 'Frankfurt', LOWER('Frankfurt'), 'Germany'),
(1233, 'Garching', LOWER('Garching'), 'Germany'),
(1179, 'Geel', LOWER('Geel'), 'Belgium'),
(1213, 'Grange', LOWER('Grange'), 'Ireland'),
(1226, 'Heidelberg', LOWER('Heidelberg'), 'Germany'),
(1161, 'Helsinki', LOWER('Helsinki'), 'Finland'),
(1204, 'Heraklion', LOWER('Heraklion'), 'Greece'),
(1167, 'Ispra', LOWER('Ispra'), 'Italy'),
(1180, 'Karlsruhe', LOWER('Karlsruhe'), 'Germany'),
(1203, 'Lisbon', LOWER('Lisbon'), 'Portugal'),
(1170, 'Ljubljana', LOWER('Ljubljana'), 'Slovenia'),
(1164, 'London', LOWER('London'), 'United Kingdom'),
(1153, 'Luxembourg', LOWER('Luxembourg'), 'Luxembourg'),
(5318, 'Madrid', LOWER('Madrid'), 'Spain'),
(4242, 'Nicosia', LOWER('Nicosia'), 'Cyprus'),
(1178, 'Non-EU cities', 'non-eu', null),
(1185, 'Other EU cities', 'other', null),
(1211, 'Prague', LOWER('Prague'), 'Czech Republic'),
(1176, 'Paris', LOWER('Paris'), 'France'),
(1190, 'Parma', LOWER('Parma'), 'Italy'),
(1183, 'Petten', LOWER('Petten'), 'The Netherlands'),
(1173, 'Riga', LOWER('Riga'), 'Latvia'),
(1217, 'Rome', LOWER('Rome'), 'Italy'),
(1219, 'Rouen', LOWER('Rouen'), 'France'),
(1230, 'Sankt-Gallen', LOWER('Sankt-Gallen'), 'Switzerland'),
(1181, 'Seville', LOWER('Seville'), 'Spain'),
(1228, 'Sofia', LOWER('Sofia'), 'Bulgaria'),
(1155, 'Strasbourg', LOWER('Strasbourg'), 'France'),
(1159, 'Stockholm', LOWER('Stockholm'), 'Sweden'),
(1189, 'Tallinn', LOWER('Tallinn'), 'Estonia'),
(1192, 'Thessaloniki', LOWER('Thessaloniki'), 'Greece'),
(1205, 'The Hague', LOWER('Hague'), 'The Netherlands'),
(1212, 'Torrejon de Ardoz', LOWER('Torrejon-de-Ardoz'), 'Spain'),
(1222, 'Toulouse', LOWER('Toulouse'), 'France'),
(1172, 'Turin', LOWER('Turin'), 'Italy'),
(1220, 'Utrecht', LOWER('Utrecht'), 'The Netherlands'),
(1165, 'Valenciennes', LOWER('Valenciennes'), 'France'),
(1209, 'Vienna', LOWER('Vienna'), 'Austria'),
(1162, 'Vigo', LOWER('Vigo'), 'Spain'),
(1199, 'Vilnius', LOWER('Vilnius'), 'Lithuania'),
(1157, 'Valletta', LOWER('Valletta'), 'Malta'),
(1207, 'Warsaw', LOWER('Warsaw'), 'Poland');